blank_issues_enabled: false
contact_links:
  - name: Feature requests
    url: https://www.notion.so/replayio/Planning-321adf7736444d398b71d2e378e53381
    about: Share suggestions so we can plan accordingly.
  - name: Product feedback
    url: https://www.notion.so/replayio/Planning-321adf7736444d398b71d2e378e53381
    about: Share feedback so we can incorporate your use cases.
  - name: Comments + Questions
    url: https://discord.gg/hw3eDwvChz
    about: Join our Discord community so we can get to know you!
