name: Run correctness tests and deploy on success
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run correctness tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
