name: Run correctness tests and deploy on success
on:
  push:
    branches:
      - master

jobs:
  #test:
  #  name: Run correctness tests
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: ./.github/actions/test
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        uses: ./.github/actions/deploy
