name: Manual Deploy

on: [workflow_dispatch]

jobs:
  build:
    name: Build webpack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.10/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Build webpack
        run: "earthly --build-arg REPLAY_RELEASE=$GIT_SHA +dist"
        env:
          GIT_SHA: ${{ github.sha }}
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tgz
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        uses: ./.github/actions/deploy
