# It would be nice if this could be commoned up with deploy.yml
name: Run tests
on: pull_request

jobs:
  build:
    name: Build webpack
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build webpack
        run: ./node_modules/.bin/webpack --mode=development
      - name: Tar up output files
        run: tar -czf dist.tgz index.html dist
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tgz
  download:
    name: Download replay browser
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Download
        run: wget https://replay.io/downloads/replay.dmg
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: replay
          path: replay.dmg
  test0:
    name: Test stripe 0
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 0/8
  test1:
    name: Test stripe 1
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 1/8
  test2:
    name: Test stripe 2
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 2/8
  test3:
    name: Test stripe 3
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 3/8
  test4:
    name: Test stripe 4
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 4/8
  test5:
    name: Test stripe 5
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 5/8
  test6:
    name: Test stripe 6
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 6/8
  test7:
    name: Test stripe 7
    runs-on: macos-latest
    needs: [build, download]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/test
        with:
          stripe: 7/8
