# It would be nice if this could be commoned up with deploy.yml
name: Run test suites
on: [pull_request, workflow_dispatch]

jobs:
  build-server:
    name: Build the Development Server
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/npm-install
      - name: Tar up output files
        run: tar -czf node_modules.tgz node_modules
      - name: "Create artifact: node_modules"
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.tgz
  download-browser:
    name: Download Replay browser
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Download
        run: wget https://static.replay.io/downloads/replay.dmg
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: replay
          path: replay.dmg
  download-node:
    name: Download node
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Download
        run: wget https://static.replay.io/downloads/macOS-replay-node
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: replay-node
          path: macOS-replay-node
  download-driver:
    name: Download recording driver
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Download
        run: wget https://static.replay.io/downloads/macOS-recordreplay.so
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: replay-driver
          path: macOS-recordreplay.so
  test0:
    name: End-to-end tests (0)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 0/9
  test1:
    name: End-to-end tests (1)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 1/9
  test2:
    name: End-to-end tests (2)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 2/9
  test3:
    name: End-to-end tests (3)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 3/9
  test4:
    name: End-to-end tests (4)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 4/9
  test5:
    name: End-to-end tests (5)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 5/9
  test6:
    name: End-to-end tests (6)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 6/9
  test7:
    name: End-to-end tests (7)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 7/9
  test8:
    name: End-to-end tests (8)
    runs-on: macos-latest
    needs: [build-server, download-browser, download-node, download-driver]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/test
        with:
          stripe: 8/9
  mock-test:
    name: Mock Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/npm-install
      - uses: ./.github/actions/setup-next
      - uses: ./.github/actions/mockTest
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/npm-install
      - name: Run tests
        run: npm test
